### ISSUE TITLE
Icon sizes are really wonky in the publications

### ISSUE THREAD

**Issue by SimonGoring** [achubaty/achubaty.github.io#1]
Hi Alex, just looking at your website, the icon for "website" on the publications tab is really big when I look at it using Chrome on Windows 10.

**Comment by achubaty** [comment]
Thanks Simon, it's because I had started using BibBase to autogenerate my publications but it is served using http and I had enabled https for my site, which means the browser complains about the mixed content and "blocks unsafe scripts", so the styling went crazy. I've reverted for now, but I'll have to find a real solution that doesn't cause the scary red X to appear in the url bar!
